Lesson5
AntonKosmovskyXB/webix-start pull request #5
Opened 2021-04-13 18:24 UTC by AntonKosmovskyXB

2021-04-13 19:24 UTC, AlexeyXB requested changes

2021-04-13 19:24 UTC, AlexeyXB commented on script.js
> +        }
После удаления у тебя форма по прежнему хранит значение. Нужно почистить.

2021-04-13 19:34 UTC, AlexeyXB requested changes

2021-04-13 19:34 UTC, AlexeyXB commented on script.js
>  function addUser() {
После добавления user лучше очистить поле ввода

2021-04-13 19:57 UTC, AlexeyXB approved these changes

2021-04-14 06:56 UTC, Zwillinge requested changes

2021-04-14 06:56 UTC, Zwillinge commented on script.js
> +                        $$("usersList").editCancel();
проще вернуть false в onClick обработчике (только не внутри промиса), чтобы по клику на иконку элемент попросут не открывался на редактирование. 

вообще там с листом что-то странное: добавление и удаление идет не у мастер коллекции, а у листа, поэтому при попытке отредактировать только что добавленный элемент с пустным именем, летит  ошибка (апдейт-то идет и на мастере в том числе, а у него этой записи нет)

а чарт зачем-то синхронизирован и с коллекцией и с листом, что и создает изначальную видимость правильной работы

2021-04-14 06:57 UTC, Zwillinge commented on script.js
> +                        $$("usersList").editCancel();
p.s. в таблице тоже return false в обработчике клика по иконке надо выносить из промиса, а то форма заполняется

2021-04-14 07:00 UTC, Zwillinge commented
при синхронизации листа с коллекцией перестала работать подсветка пользователей в листе. дело в том, что для синхронизироанных вью схема работает только для мастер. и добавление $css надо переносить на мастер коллекцию

2021-04-14 08:05 UTC, AntonKosmovskyXB commented on script.js
> +                        $$("usersList").editCancel();
Исправлено

2021-04-14 08:13 UTC, Zwillinge approved these changes

2021-04-14 08:14 UTC, merged